services:
  vintagestory-server-stable:
    container_name: vintagestory_server
    environment:
      SERVER_PASSWORD: passsword #Change this to a secure password
    image: devidian/vintagestory:latest
    ports:
      - '42420:42420'
    restart: unless-stopped
    volumes:
      - /path/to/save:/gamedata
